title: "Ghif's Research Notes"
author: "Muhammad Ghifary"
description: "\"Research means that you don't know, but are willing to find out\" - Charles F. Kettering"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
# minimal: false             # use a dark header

# Build settings
markdown: kramdown
kramdown:
  # math_engine: katex
  math_engine: mathjax
# mathjax: true
usemathjax: true

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mghifary@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ghif"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
 disqus_shortname: "discuss"    # see https://disqus.com/
 # isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
